services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"   # المستخدم يدخل على ده بس
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my_frontend
    expose:
      - "8501"   

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_backend
    expose:
      - "8000"   
